# Generated by Django 3.2.6 on 2022-04-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refeer',
            fields=[
                ('id_refeer', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='sin descripción', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'refeers',
                'db_table': 'refeer',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='refeer',
            index=models.Index(fields=['id_refeer'], name='refeer_id_refe_9254a4_idx'),
        ),
    ]
