# Generated by Django 3.2.6 on 2022-05-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaRefeer',
            fields=[
                ('id_lecturarefeer', models.AutoField(primary_key=True, serialize=False)),
                ('sensor', models.IntegerField(default=0)),
                ('lectura', models.IntegerField(default=0)),
                ('es_tierra', models.BooleanField(default=False)),
                ('id_refeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.refeer')),
            ],
            options={
                'verbose_name_plural': 'lecturasrefeers',
                'db_table': 'lecturarefeer',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='lecturarefeer',
            index=models.Index(fields=['id_lecturarefeer'], name='lecturarefe_id_lect_4dca45_idx'),
        ),
    ]
