# Generated by Django 3.2.6 on 2022-05-04 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lecturarefeer_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id_alarma', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('id_refeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.refeer')),
            ],
            options={
                'verbose_name_plural': 'alarmas',
                'db_table': 'alarma',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='alarma',
            index=models.Index(fields=['id_alarma'], name='alarma_id_alar_1759e6_idx'),
        ),
    ]
