# Generated by Django 3.2.6 on 2022-05-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220504_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='aire_tierra',
            field=models.IntegerField(default=0),
        ),
    ]
