# Generated by Django 3.2.6 on 2022-05-04 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alarma_aire_tierra'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
