# Generated by Django 3.2.6 on 2022-05-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alarma_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='on',
            field=models.BooleanField(default=False),
        ),
    ]
