# Generated by Django 3.2.6 on 2022-05-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alarma_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='treshhold',
            field=models.IntegerField(default=0),
        ),
    ]
