# Generated by Django 3.2.6 on 2022-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alarma_treshhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
