# Generated by Django 3.2.6 on 2022-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alarma_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='color',
            field=models.CharField(default='info', max_length=200),
        ),
    ]
