# Generated by Django 3.2.6 on 2022-05-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alarma_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarma',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alarma',
            name='inicio',
            field=models.DateField(),
        ),
    ]
