# Generated by Django 3.2.6 on 2022-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220518_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeer',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
