# Generated by Django 3.2.6 on 2022-05-19 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_refeer_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmaContacto',
            fields=[
                ('id_alarmacontacto', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('id_alarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alarma')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'alarmas de contactos',
                'db_table': 'alarmacontacto',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='alarmacontacto',
            index=models.Index(fields=['id_alarmacontacto'], name='alarmaconta_id_alar_032637_idx'),
        ),
    ]
